### ISSUE TITLE
Unable to view friend wishlist

### ISSUE THREAD

**Issue by smarota17** [landog893/Gifter-2#10]
When I try to view a friend's wishlist by clicking the "View Wishlist of friend" button, I get a "Missing Submit Button" error with the following description: 

"This form has no submit button, which means that user interactions will never be sent to your Streamlit app.
To create a submit button, use the st.form_submit_button() function.
For more information, refer to the [documentation for forms](https://docs.streamlit.io/library/api-reference/control-flow/st.form)."

I think this might be an issue related to the new "email" parameter for accounts, will continue debugging.

**Comment by smarota17** [comment]
Fixed! I had accidentally made some changes to the add friend functionality that caused the code to break. It should be working now.

**Comment by saminur** [comment]
The issue has been resolved and made changes for the problem in the following commit.
16d710e9eff7024ca8cb5946a89344e34b22fd97
