### ISSUE TITLE
add features for freindlist

### ISSUE THREAD

**Issue by saminur** [landog893/Gifter-2#13]
Currently, the only thing we have for friends is the id and name and wish list. we are planning to add more information for the friends

**Comment by saminur** [comment]
This feature enhances a searching friend in the system by using the first name, last name or part of names. The query will check if there is a match of the name in the database. If so, it will return a list of users with the same match. 

After that, the user could add any of them as a friend to their friend list.

**Comment by saminur** [comment]
d4fe013e61c93feda26a75825ea44bc8f7ff6588
This is the commit message for the desired changes made for this one!

**Comment by smarota17** [comment]
Great work!! The commit looks awesome.
