### ISSUE TITLE
User registration 

### ISSUE THREAD

**Issue by saminur** [landog893/Gifter-2#3]
After entering into the user registration process we can not return to the main application page. Need to resolve and the inputs are not used for the login. Only id is used which is a very inefficient design. 

We need to fix the registration process.

**Comment by saminur** [comment]
Include attributes like username, password, first name and last name for the registration and check whether a user is creating a unique user name.

**Comment by saminur** [comment]
Now in the registration process, someone will need to provide valid username input to make the registration complete. Also, we need to provide an email and password in the registration process.
2f22d9dd8f8087a017acd6687340fb857c49e86b

**Comment by smarota17** [comment]
Thanks for looking into this!
