### ISSUE TITLE
Issue with email functionality

### ISSUE THREAD

**Issue by smarota17** [landog893/Gifter-2#38]
For some reason the email functionality isn't properly formatting the email body (wishlist is incorrectly formatted, sometimes the subject line doesn't appear).

**Comment by smarota17** [comment]
To fix this issue I had to use SSL, stmplib, and ensure that all the objects I was trying to add in the string were strings and not objects. Commit with the fix is here: 565bc8e73f280f52b8c5d1b0d3ddf42d6dd04102

**Comment by JesseChen1031** [comment]
That works! Awesome
