### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by saminur** [landog893/Gifter-2#4]
Need to utilize the user credentials instead of using stored id.

**Comment by saminur** [comment]
Implemented the login with the user name. Provided validation to check valid username and password for user login

**Comment by saminur** [comment]
This issue has been resolved. In login, it will check whether someone is trying to log in using a valid username and password. If not, the app will send a message to use valid login credentials.
2f22d9dd8f8087a017acd6687340fb857c49e86b
d44a39f00f7588c95262a61d31e8aba4ef9dc4fa
1a13c15297f67dab9cbda3df8c36e2a183cf8657

**Comment by smarota17** [comment]
Thanks for listing all the commits you made. The code looks great.
